apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql  
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: whatsbusy-db
        - name: MYSQL_USER
          value: jainish  
        - name: MYSQL_PASSWORD
          value: jainish
        - name: MYSQL_ROOT_PASSWORD
          value: root
        image: mysql:5.7
        # args:
        #   - "--ignore-db-dir=lost+found" #CHANGE
        name: mysql
        ports:
        - containerPort: 3306
        # volumeMounts:
        # - mountPath: /var/lib/mysql
        #   name: mysql-database-data-volume
      restartPolicy: Always
      # volumes:
      # - name: mysql-database-data-volume
      #   persistentVolumeClaim:
      #     claimName: mysql-database-data-volume

---
    
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  type: LoadBalancer
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    app: mysql
