apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: whatsbusy
  name: whatsbusy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whatsbusy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%    
    type: RollingUpdate 
  template:
    metadata:
      labels:
        app: whatsbusy
      name: whatsbusy
    spec:
      containers:
        - env:
          - name: DATABASE
            value: whatsbusy-db
          - name: USER
            value: jainish
          - name: PASSWORD
            value: jainish
          - name: PORT
            value: "3306"
          - name: HOST
            value: mysql  
          image: jainishparikh/whatsbusy
          name: to-do-container
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
    
apiVersion: v1
kind: Service
metadata:
  labels:
    app: whatsbusy-service
  name: whatsbusy-service
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP 
  selector:
    app: whatsbusy
  sessionAffinity: ClientIP
  type: LoadBalancer  

    
          
