# Generated by Django 2.2 on 2020-05-03 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20200503_0030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
