# Generated by Django 2.2 on 2020-05-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='trial_taken',
            field=models.BooleanField(default=False),
        ),
    ]
