# Generated by Django 2.2 on 2020-05-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_subscription_trial_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='days_left',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='trial_taken',
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_customer_id',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription',
            field=models.BooleanField(default=False),
        ),
    ]
