# Generated by Django 2.2 on 2020-05-03 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_auto_20200503_0352'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
