# Generated by Django 2.2 on 2020-05-03 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
