# Generated by Django 2.2 on 2020-05-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_plan_id',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
