# Generated by Django 2.2 on 2020-05-03 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0012_auto_20200503_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_plan_id',
        ),
    ]
