# Generated by Django 2.2 on 2020-05-03 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0014_auto_20200503_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='subscription',
            new_name='active',
        ),
    ]
