# Generated by Django 2.2 on 2020-05-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0015_auto_20200503_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='stripe_customer_id',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_token_id',
            field=models.CharField(default='', max_length=500),
        ),
    ]
